server:
  name: "secretservice"
  port: 3001
  domain: "secretservice.davewales.au"
  getkey: "45h4h45h4h45h45h"
  postkey: "5h4t34t34t45y434t"
database: 
  name: "secrets.db"
  key: "5fccbfb79fff470b92dcf89aa5c0dd3c"
captcha:
  enabled: false
  sitekey: "6Lc2xb0jAAAAALSK1gPfZpdc0Nu3-EJy-djnJj-J"
  secretkey: "6Lc2xb0jAAAAADJeRKhxkakOwpPQxQAy5yE9fefI"
  score: 0.8
